baseurl: http://datascience.utu.fi
title: Turku Data Science Group
theme: hugo-universal-theme
languageCode: en-us
defaultContentLanguage: en
disqusShortname: devcows
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
googleAnalytics: 'G-3HREPRC83G'
pagination:
  pagerSize: 10
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: edu
      name: Edu
      url: /edu/
      weight: 4
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 9
    - identifier: code
      name: Code
      url: /code/
      weight: 5
    #- identifier: media
    #  name: Media
    #  url: /media/
    #  weight: 6
    #- identifier: publications
    #  name: Publications
    #  url: /publications/
    #  weight: 7
    - identifier: research
      name: Research
      url: /research/
      weight: 3
    - identifier: team
      name: Team
      url: /team/
      weight: 7
  topbar:
    - name: GitHub
      pre: <i class='fab fa-2x fa-github'></i>
      url: https://github.com/openresearchlabs/
      weight: 1
    - name: Twitter
      pre: <i class='fab fa-2x fa-twitter'></i>
      url: https://twitter.com/openreslabs
      weight: 3
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url: mailto:leo.lahti@utu.fi
      weight: 4
params:
  about_us: <p>Turku Data Science Group.</p>
  address: "<p class=\"text-uppercase\"><strong>Turku Data Science Group</strong>\n        <br>University of Turku\n        <br>Department of Computing\n        <br>Turku\n        <br>Finland\n
    \       <br>\n        <strong></strong>\n      </p>\n      "
  author: DevCows
  carousel:
    enable: yes
  #clients:
  #  enable: yes
  #  subtitle: ''
  #  title: Our Clients
  contact_form_ajax: no
  copyright: Copyright (c) 2020-2025, Leo Lahti; some rights reserved.
  date_format:  2006-01-02
  #date_format: 2020-12-15
  default_sharing_image: img/sharing-default.png
  defaultDescription: Site template made by devcows using hugo
  defaultKeywords:
    - devows
    - hugo
    - go
  enableGoogleMaps: yes
  facebook_site: ''
  features:
    enable: yes
  formspree_action: https://formspree.io/sample/of/endpoint
  latitude: '-12.043333'
  logo: img/logopic/university_turku.png # img/orcid_qrcode_leolahti_small.png
  logo_small: img/logo-small.png
  longitude: '-77.028333'
  mainSections: blog
  #see_more:
  #  enable: yes
  #  icon: far fa-file-alt
  #  link_text: Check other homepages
  #  link_url: '#'
  #  subtitle: We have prepared for you more than 40 different HTML pages, including
  #    5 variations of homepage.
  #  title: Do you want to see more?
  #style: default
  #testimonials:
  #  enable: yes
  #  subtitle: We have worked with many clients and we always like to hear they come
  #    out from the cooperation happy and satisfied. Have a look what our clients said
  #    about us.
  #  title: Testimonials
  topbar:
    enable: yes
    text: "<p class=\"hidden-sm hidden-xs\">Contact us on first.last@utu.fi</p>\n
      \     <p class=\"hidden-md hidden-lg\"><a href=\"#\" data-animate-hover=\"pulse\"><i
      class=\"fas fa-phone\"></i></a>\n      <a href=\"#\" data-animate-hover=\"pulse\"><i
      class=\"fas fa-envelope\"></i></a>\n      </p>\n      "
  twitter_site: GoHugoIO
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
Permalinks:
  blog: /blog/:year/:month/:day/:filename/
